### ISSUE TITLE
multi-row tab bar

### ISSUE THREAD

**Issue by GiftWolf** [RobertZenz/ThinTabs#2]
I use the Tab Mix Plus addon to have a multi-row tab bar. With ThinTabs installed this feature is broken. Only one row is displayed.

**Comment by RobertZenz** [comment]
I've just committed the necessary changes with 43fc8ae (was quite a scavenger hunt) to support the Tab Mix Plus multi-row bar. There is still some small changes necessary for correct support, but I think I should get those done right now.

I need to make another set of tests on my Windows machine at work to verify that it still works correctly on Windows, and if these tests succeed (or the problems are easy to fix) I'm very confident that I can do a build tomorrow and upload it to AMO. If there is something blocking that plan, it will be next week before I have the chance to look into it.

Sorry for the (damn long) delay on this one.

**Comment by RobertZenz** [comment]
I've just uploaded 1.5.3 to AMO. It should get available within the next week I think.

If there are any remaining issues, please open a new issue.
