### ISSUE TITLE
AddOn disables "multiprocess" support

### ISSUE THREAD

**Issue by derGhostrider** [RobertZenz/ThinTabs#9]
As soon as the ThinTabs AddOn is installed Firefox disables the multiprocess feature, as ThinTabs is not compatible with this feature.

Is it possible tp correct this issue?
Thanks!

**Comment by RobertZenz** [comment]
This should be fixed with [v1.7](https://github.com/RobertZenz/ThinTabs/releases/tag/v1.7).

Please note that I stopped distributing updates via addons.mozilla.org, you can get 1.7 here from GitHub.
